AlanMorel/MapleServer2

.gitignore
Maple2Storage/Types/Color.cs
Maple2Storage/Types/HairData.cs
MapleServer2/Data/AccountStorage.cs
MapleServer2/Network/PacketRouter.cs
MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
MapleServer2/PacketHandlers/Login/CharacterManagementHandler.cs
MapleServer2/PacketHandlers/Login/LoginHandler.cs
MapleServer2/PacketHandlers/Login/ServerEnterPacketHandler.cs
MapleServer2/Packets/Helpers/ItemPacketHelper.cs
MapleServer2/Types/Item.cs
MapleServer2/Types/Player.cs

- Added static class AccountStorage for dynamic character data
- Removed references to StaticAccountStorage
- Implemented character creation
- Added missing character and packet information for character appearance

Feat: character creation

---

MapleServer2/PacketHandlers/Game/UserChatHandler.cs
MapleServer2/Packets/ChatPacket.cs
MapleServer2/Servers/Game/FieldManager.cs

- Super(hardcoded item), World and Channel.

Adding type of chat

---

MapleServer2/Constants/SendOp.cs
MapleServer2/Data/AccountStorage.cs
MapleServer2/PacketHandlers/Common/ResponseVersionHandler.cs
MapleServer2/PacketHandlers/Game/FieldEnterHandler.cs
MapleServer2/PacketHandlers/Game/MailHandler.cs
MapleServer2/PacketHandlers/Login/CharacterManagementHandler.cs
MapleServer2/Packets/Helpers/MailPacketHelper.cs
MapleServer2/Packets/ItemPacket.cs
MapleServer2/Packets/MailPacket.cs
MapleServer2/Servers/Game/GameSession.cs
MapleServer2/Tools/GuidGenerator.cs
MapleServer2/Types/Mail.cs
MapleServer2/Types/Mailbox.cs
MapleServer2/Types/Player.cs

-Added Mail type to hold mail data
-Added Mailbox type to hold and manage mail
-Added handlers and packet files for mail
-Handles notify, send, open, read, collect, batch read, batch collect
-Blackmarket mail is not handled yet
-Added Item packet, not sure if this is only used for mail or not
-Added tick count to AccountStorage to fix timestamp issues
-Added new tool GuidGenerator to handle creating new uids
-Added a Mailbox to the GameSession
-Added test data to FieldEnterHandler with different types of mail

Feat: mail

---

MapleServer2/MapleServer.cs
MapleServer2/PacketHandlers/Game/UserChatHandler.cs

Feat: Properly broadcasting chat
Feat: Added BroadcastAll and BroadcastPacketAll to MapleServer
This lets you access all players currently online on the server (not just the current field)

Added chat functionality (whispers, world chat) and BroadcastAll

---

MapleServer2/Data/Static/MapEntityStorage.cs
MapleServer2/Tools/GameCommandActions.cs

map command

---

MapleServer2/Types/Player.cs
MapleServer2/Types/PlayerStats.cs

Moving all the new stats that was being add every single time. Improve readability

Smaller Fix: Making less redundant code for Player

---

.gitignore
MapleServer2/Constants/RecvOp.cs
MapleServer2/Constants/SendOp.cs
MapleServer2/PacketHandlers/Game/RequestTaxiHandler.cs
MapleServer2/PacketHandlers/Game/RequestWorldMapHandler.cs
MapleServer2/Packets/WorldMapPacket.cs

Added: WorldMap Loading
Added: Rotors Taxi (for now, it works with mesos only)
+ small fix in MailHandler

Added: WorldMap Loading & Rotors Taxi Request with Mesos

---

MapleServer2/PacketHandlers/Game/RequestTaxiHandler.cs

+ Added a bool to check if user has enough mesos/merets before sending player to the target map
- Taxi stops don't work yet tho

ADDED: Request taxi by car

---

MapleServer2/Constants/RecvOp.cs
MapleServer2/PacketHandlers/Game/PartyHandler.cs
MapleServer2/PacketHandlers/Game/UserChatHandler.cs
MapleServer2/Packets/PartyPacket.cs
MapleServer2/Servers/Game/GameServer.cs
MapleServer2/Tools/PartyManager.cs
MapleServer2/Types/Party.cs
MapleServer2/Types/Player.cs

Working with up to 10 players (Tested to 4). No party finder yet. 
Some bugs:
- If someone joins a party that has had the leader changed it sometimes will not show the new leader for the player who joined.
- Sometimes parties may become out of sync (party member seems to be in the party but isn't)
Not yet implemented: Ready Check, Vote to Kick, Dungeon Entrance, Party buffs

Feat: Parties

---

GameDataParser/App.config

- Updating OUTPUT to be at the folder that needs to be

Updating App.Config

---

MapleServer2/MapleServer.cs
MapleServer2/PacketHandlers/Game/BreakableHandler.cs
MapleServer2/PacketHandlers/Game/PlayerTitleHandler.cs
MapleServer2/PacketHandlers/Game/RequestTaxiHandler.cs
MapleServer2/PacketHandlers/Game/StateHandler.cs
MapleServer2/PacketHandlers/Game/UserSyncHandler.cs
MapleServer2/PacketHandlers/Game/VibrateHandler.cs
MapleServer2/Packets/BreakablePacket.cs
MapleServer2/Packets/TaxiPacket.cs
MapleServer2/Packets/VibratePacket.cs
MapleServer2/Servers/Game/FieldManager.cs
MapleServer2/Types/Player.cs

Fix: Made the resolve <packet> command actually work. You still need 1 player on the server however.
Fix: Crash when opening Trophy menu in PlayerTitleHandler
Fix: ClientTicks not being updated
Feat: Created state handler for jumping/landing (probably for trophies)

Feat: Vibrate and Breakables

---

MapleServer2/Packets/UserBattlePacket.cs
MapleServer2/Tools/GameCommandActions.cs

- Adding in Commands for player be able to get out of combat mode.

Adding UserBattlePacket

---

MapleServer2/PacketHandlers/Game/ClubHandler.cs
MapleServer2/Packets/ClubPacket.cs
MapleServer2/Servers/Game/GameServer.cs
MapleServer2/Tools/ClubManager.cs
MapleServer2/Types/Club.cs
MapleServer2/Types/Player.cs

A club no longer exists if no other member accepts the invite to create one.
I renamed some packets after diving deeper to invitations.
Invites are still not fully implemented yet.

Clubs - Fixed how clubs are created

---

MapleServer2/PacketHandlers/Game/ClubHandler.cs
MapleServer2/Packets/ClubPacket.cs
MapleServer2/Types/Club.cs

I commented on what needs to be done still but the biggest two things that needs to be addressed is removing club members out of party members and disbanding/reassigning leadership. I wanted to at least get this out for any comments and feedback

Club Invites, Leaving, Renaming, and Buff settings

---

.editorconfig

`dotnet tool install -g dotnet-format`
`dotnet format mapleserver2.sln`

Add editorconfig for linting

---

MapleServer2/PacketHandlers/Game/GuildHandler.cs
MapleServer2/Packets/GuildPacket.cs
MapleServer2/Servers/Game/GameServer.cs
MapleServer2/Tools/GuildManager.cs
MapleServer2/Types/Guild.cs
MapleServer2/Types/Player.cs

Start of guild system. A lot of names for the handles/packets are placeholders until it starts getting more fleshed out.

Guild creation

---

GameDataParser/Parsers/ItemParser.cs
GameDataParser/Parsers/MapEntityParser.cs
GameDataParser/Parsers/SkillParser.cs
MapleServer2/Packets/NoticePacket.cs
MapleServer2/Tools/GameCommandActions.cs

- Created Notice packet class
- Added command to send server-wide notice
- Changed GameDataParsers to always create new file

Feat: Server notices

---

MapleServer2/PacketHandlers/Game/SkillHandler.cs
MapleServer2/Packets/SkillDamagePacket.cs
MapleServer2/Packets/SkillUsePacket.cs

- Added SkillPacket ( SKILL_USE & SKILL_DAMAGE)
- Added SkillHandle.
Still working on how mobs are spawn and deducting the damage is done by the skill, because mobs are'nt modifying any stats and they need to be pass on the field, so not sure on how to test this without that.

Add: Skill Packet & Handle.

---

MapleServer2/Enums/CurrencyType.cs
MapleServer2/PacketHandlers/Game/GuildHandler.cs
MapleServer2/PacketHandlers/Game/RequestTaxiHandler.cs
MapleServer2/Packets/MeretsPacket.cs
MapleServer2/Packets/MesosPacket.cs
MapleServer2/Packets/ServerEnterPacket.cs
MapleServer2/Tools/GameCommandActions.cs
MapleServer2/Types/Currency.cs
MapleServer2/Types/Player.cs
MapleServer2/Types/Wallet.cs

- Added ENUM CurrencyType
- Added Class Currency
- Added Class Wallet
Added two commands for testing purposes:
- setmesos / setmerets 
ISSUE: Missing packets to update the client for:
- ValorToken
- Treva
- Rue
- HaviFruit
- MesoToken

Feature Currency

---

MapleServer2/Enums/CurrencyType.cs
MapleServer2/Packets/WalletPacket.cs
MapleServer2/Tools/GameCommandActions.cs
MapleServer2/Types/Currency.cs

Added packet for HaviFruit, Rue, Treva and Valor;
Added commands for testing purposes.

Feature(Wallet): Added packets

---

MapleServer2/PacketHandlers/Game/GuildHandler.cs
MapleServer2/Packets/GuildPacket.cs
MapleServer2/Tools/GuildManager.cs
MapleServer2/Types/Guild.cs

I'm calling these initial features or just adding in the packets because they're not fully functioning. and I'll most likely need either someone else to assist on it or implement it
Guild listing is not working as intended due to it needing to grab a list of the guilds there are.
Applying is not working as intended because this will need some way to store applications with the respective player's info
Rank changing is not working as intended because this will also need to be stored for each member
Buff packets are there but will need buffs to be fully functioning for this to work
Hiring NPC services are sort of added. Need to properly implement a way to update a guild with it. Once guild housing is implemented, this can be used for it.
#83

Guild packets for guild listing, applying, rank changing, buffs, and services

---

Ms2Database/Controllers/AccountManager.cs
Ms2Database/Controllers/CharacterManager.cs
Ms2Database/DBClasses/Account.cs
Ms2Database/DBClasses/Ms2DBContext.cs
Ms2Database/DbClasses/Character.cs
Ms2Database/Ms2Database.csproj
Ms2Database/Program.cs

Missing Inventory slots, Equipment slots, Skill tree, etc. 
Single value variables are all implemented. (level, jobid, name, etc.)

DB Character (With minor Account changes)

---

GameDataParser/Files/Export/ExpMetadataExport.cs
GameDataParser/Files/Export/InsigniaMetadataExport.cs
GameDataParser/Files/Export/ItemMetadataExport.cs
GameDataParser/Files/Export/MapMetadataExport.cs
GameDataParser/Files/Export/PrestigeMetadataExport.cs
GameDataParser/Files/Export/SkillMetadataExport.cs
GameDataParser/Parsers/ExpParser.cs
GameDataParser/Parsers/InsigniaParser.cs
GameDataParser/Parsers/ItemParser.cs
GameDataParser/Parsers/MapEntityParser.cs
GameDataParser/Parsers/PrestigeParser.cs
GameDataParser/Parsers/SkillParser.cs
GameDataParser/Program.cs
MapleServer2/Tools/GameCommandActions.cs

- Added multithreading to GameDataParser
- Added console spinner to indicate it is still running
- Fix ItemParser rarity parsing to default to `1` if rarity not found
- Etc: small fix to GameCommandAction to allow item rarity to be set

Feat: Multi-threaded GameDataParser

---

MaplePacketLib2/Tools/PacketWriter.cs
MapleServer2/MapleServer.cs
MapleServer2/Packets/ChatStickerPacket.cs
MapleServer2/Packets/ClubPacket.cs
MapleServer2/Packets/FieldObjectPacket.cs
MapleServer2/Packets/GemPacket.cs
MapleServer2/Packets/GuildPacket.cs
MapleServer2/Packets/MatchPartyPacket.cs
MapleServer2/Packets/NoticePacket.cs
MapleServer2/Packets/PartyPacket.cs
MapleServer2/Packets/PremiumClubPacket.cs
MapleServer2/Packets/PrestigePacket.cs
MapleServer2/Packets/ResponseCubePacket.cs

- Small addition to packet writer that dynamically writes any enum
- Replace WriteMode with WriteEnum
- Small fix to server command for sending packets directly
- Small fix to WriteString to include length

Feat: WriteEnum

---

GameDataParser/Parsers/ItemParser.cs
Maple2Storage/Types/Metadata/ItemMetadata.cs
MapleServer2/Data/Static/ItemMetadataStorage.cs
MapleServer2/PacketHandlers/Game/Helpers/ItemUseHelper.cs
MapleServer2/PacketHandlers/Game/RequestItemUseHandler.cs
MapleServer2/PacketHandlers/Game/RequestItemUseMultipleHandler.cs
MapleServer2/Tools/InventoryController.cs
MapleServer2/Types/Item.cs

Added Recommend Jobs, Rarity ,Min / Max Amount, Smart Drop Rate, Enchants
Correctly handling boxes with random options and boxes that have more drop rate for your class.

Fix: ItemParser

---

GameDataParser/Files/Export/PrestigeMetadataExport.cs
GameDataParser/Files/Hash.cs
GameDataParser/Parsers/PrestigeParser.cs
GameDataParser/Program.cs
Maple2Storage/Types/GemSlot.cs
Maple2Storage/Types/Metadata/ItemMetadata.cs
Maple2Storage/Types/Metadata/PrestigeMetadata.cs
MapleServer2/Constants/Skills/SkillTreeOrdered.cs
MapleServer2/Data/Static/ItemMetadataStorage.cs
MapleServer2/Data/Static/PrestigeMetadataStorage.cs
MapleServer2/MapleServer.cs
MapleServer2/PacketHandlers/Game/GuildHandler.cs
MapleServer2/PacketHandlers/Game/Helpers/ItemUseHelper.cs
MapleServer2/PacketHandlers/Game/PrestigeHandler.cs
MapleServer2/PacketHandlers/Game/RequestCubeHandler.cs
MapleServer2/PacketHandlers/Game/RequestGemEquipmentHandler.cs
MapleServer2/PacketHandlers/Game/RequestItemUseHandler.cs
MapleServer2/PacketHandlers/Game/RequestItemUseMultipleHandler.cs
MapleServer2/PacketHandlers/Game/StatPointHandler.cs
MapleServer2/Packets/GemPacket.cs
MapleServer2/Packets/JobPacket.cs
MapleServer2/Packets/NoticePacket.cs
MapleServer2/Packets/ResponseCubePacket.cs
MapleServer2/Packets/SkillBookTreePacket.cs
MapleServer2/Types/SkillTab.cs
Ms2Database/DbClasses/Inventory.cs
Ms2Database/DbClasses/Item.cs
Ms2Database/DbClasses/SkillTree.cs
Ms2Database/Program.cs

- Fix jobgroupid to be job
- Convert recommendjob list from int to Job enum
- Cleanup formatting (dotnet-format)

Fix: ItemUseHelper

---

MapleServer2/PacketHandlers/Game/InsigniaHandler.cs
MapleServer2/PacketHandlers/Game/PremiumClubHandler.cs
MapleServer2/Types/Player.cs

Added bool IsVIP.
Added the VIP case in function CanEquipInsignia()

fix: Handling insignia case VIP

---

MapleServer2/PacketHandlers/Game/UserSyncHandler.cs

Fix: Out of bounds teleport

---

MapleServer2/PacketHandlers/Game/BuddyEmoteHandler.cs
MapleServer2/PacketHandlers/Game/EmoteHandler.cs
MapleServer2/Packets/BuddyEmotePacket.cs
MapleServer2/Packets/EmotePacket.cs

- Remove unused using statements
- Remove unused parameters
- Converted methods that do not access instance members to static

Cleanup: emote and buddy emote files

---

MapleServer2/Servers/Game/FieldManager.cs
MapleServer2/Types/Mob.cs
MapleServer2/Types/Npc.cs

Add monsters to field as Mob Object instead of Npc Object.

Fix: NullPointerException on attacking mobs

---

MapleServer2/PacketHandlers/Game/Helpers/ItemUseHelper.cs
MapleServer2/Tools/GameCommandActions.cs
MapleServer2/Types/Item.cs

- Removed rarity option from ItemStats constructor
- Fixed ItemStats for rewards for boxes

Fix: ItemStats

---

MapleServer2/PacketHandlers/Game/RequestItemInventoryHandler.cs
MapleServer2/PacketHandlers/Game/RequestTaxiHandler.cs
MapleServer2/Packets/ItemInventoryPacket.cs
MapleServer2/Tools/InventoryController.cs
MapleServer2/Types/Inventory.cs
MapleServer2/Types/Player.cs
MapleServer2/Types/Wallet.cs

Added handling for expanding inventory.
Removed hard coded modes, added enum **InventoryMode**;
Added function `Expand()`.
Added a check on `Inventory.Add()` so packet is not send if item can't be added to inventory;
Added function to `ExpandInventory()`.
Added default and extra size for each inventory tab.

Feat: Expand inventory & Inventory tab size

---

MapleServer2/PacketHandlers/Game/RequestCubeHandler.cs

Fix pickup map object

---

MapleServer2/Data/AccountStorage.cs
MapleServer2/PacketHandlers/Game/SkillHandler.cs
MapleServer2/Packets/FieldPacket.cs
MapleServer2/Packets/SkillDamagePacket.cs
MapleServer2/Packets/SkillUsePacket.cs
MapleServer2/Packets/StatPacket.cs
MapleServer2/Servers/Game/FieldManager.cs
MapleServer2/Types/DamageHandler.cs
MapleServer2/Types/FieldState.cs
MapleServer2/Types/Item.cs
MapleServer2/Types/Mob.cs
MapleServer2/Types/Player.cs
MapleServer2/Types/SkillCast.cs
MapleServer2/Types/SkillTab.cs

- Add: a `Priest` character. (it covers almost all situation on skills)
- Add: `SkillCast` class for the skill that is being use in the moment.
- Update: SkillUse, SkillHandler and SkillDamage to use SkillCast.
- Add: `DamageHandler` class container of the damage
- Add: default items for Priest character
- Update: `stats.hp.max = stats.hp.total` for mobs. In order to make calculations, it has to substract/add from `Max`. Then `Total` is used for the hp bar.
- Fix: `SkillJobSub` for those job that has sub skill in `Xml/table/job` but that id isn't an actual existing skill on `Xml/skill`
- Fix: Mobs now disappear from field when they die

Feat: Adding WIP Damage

---

.editorconfig
GameDataParser/Crypto/AESCipher.cs
GameDataParser/Crypto/Common/PackFileEntry.cs
GameDataParser/Parsers/MapEntityParser.cs
GameDataParser/Parsers/NpcParser.cs
Maple2Storage/Types/Coord.cs
Maple2Storage/Types/Metadata/AchieveMetadata.cs
Maple2Storage/Types/Metadata/ItemMetadata.cs
Maple2Storage/Types/Metadata/MapEntityMetadata.cs
Maple2Storage/Types/Metadata/MasteryMetadata.cs
Maple2Storage/Types/Metadata/RecipeMetadata.cs
MapleServer2/Network/Session.cs
MapleServer2/PacketHandlers/Game/ChangeAttributesHandler.cs
MapleServer2/PacketHandlers/Game/ItemEquipHandler.cs
MapleServer2/Packets/SkillUsePacket.cs
MapleServer2/Types/DamageHandler.cs
MapleServer2/Types/SkillCast.cs
Ms2Database/Controllers/AccountManager.cs
Ms2Database/Controllers/CharacterManager.cs
Ms2Database/Controllers/EquipmentManager.cs
Ms2Database/Controllers/InventoryManager.cs
Ms2Database/Controllers/SkillTreeManager.cs

**No logic was changed.**
Changed `csharp_prefer_braces` severity to warning.

Cleanup: Resolve all issues identified in .editorconfig

---

MapleServer2/PacketHandlers/Game/RequestItemBreakHandler.cs
MapleServer2/Tools/InventoryController.cs
MapleServer2/Types/Player.cs

- New function `Consume` in `InventoryController.cs`.
- Fixed removing the correct amount of items from inventory.
- Fixed giving the correct amount of rewards.

Fix: Dismantle

---

GameDataParser/Hash/ms2-map-metadata-hash
GameDataParser/Parsers/MapEntityParser.cs
GameDataParser/Parsers/MapParser.cs
GameDataParser/Program.cs
Maple2Storage/Types/Block.cs
Maple2Storage/Types/Coord.cs
Maple2Storage/Types/Metadata/MapMetadata.cs
MapleServer2/Data/Static/MapMetadataStorage.cs
MapleServer2/PacketHandlers/Game/MoveFieldHandler.cs
MapleServer2/PacketHandlers/Game/UserSyncHandler.cs
MapleServer2/Packets/GuideObjectPacket.cs
MapleServer2/Types/Player.cs

- Map parser;
- Adjusted out of bounds teleport to check if closest block exists on map.
- Added Parse(string) to Coord classes

Feat: Map block parser

---

MapleServer2/PacketHandlers/Game/ChatStickerHandler.cs
MapleServer2/PacketHandlers/Game/GroupChatHandler.cs
MapleServer2/Packets/ChatStickerPacket.cs
MapleServer2/Packets/GroupChatPacket.cs
MapleServer2/Servers/Game/GameServer.cs
MapleServer2/Tools/GroupChatManager.cs
MapleServer2/Types/GroupChat.cs
MapleServer2/Types/Player.cs

- Implemented Group Chats
- Added a packet handler and packet for handling chat stickers in group chats.
The most underused lame feature in the game.
Please enjoy.
P.S. This is my first time using arrays in action. So pls let me know if there's any better ways to handle things. I'm hoping I can carry over what I learn to Clubs

Feature: Group Chats

---

MapleServer2/Enums/CurrencyType.cs
MapleServer2/PacketHandlers/Game/RequestHomeBankHandler.cs
MapleServer2/PacketHandlers/Game/RequestItemBreakHandler.cs
MapleServer2/PacketHandlers/Game/RequestItemStorage.cs
MapleServer2/Packets/HomeBank.cs
MapleServer2/Packets/StorageInventory.cs
MapleServer2/Types/BankInventory.cs
MapleServer2/Types/Currency.cs
MapleServer2/Types/DismantleInventory.cs
MapleServer2/Types/Player.cs
MapleServer2/Types/Wallet.cs

- Handling packets for `REQUEST_HOME_BANK` and `REQUEST_ITEM_STORAGE`.
- Packet writing for `HOME_BANK` and `STORAGE_INVENTORY`.
- New class `BankInventory` and `DismantleInventory`.
- Added **CurrencyType** `Bank` and **Currency** `Bank` to **Wallet**.

Feat: Bank inventory

---

GameDataParser/Parsers/MapEntityParser.cs
GameDataParser/Parsers/NpcParser.cs
Maple2Storage/Types/Block.cs
MapleServer2/PacketHandlers/Game/GroupChatHandler.cs
MapleServer2/PacketHandlers/Game/RequestItemLockHandler.cs
MapleServer2/PacketHandlers/Game/StatPointHandler.cs
MapleServer2/Packets/ItemLockPacket.cs
MapleServer2/Types/LockInventory.cs
MapleServer2/Types/Player.cs

- Handling item lock.
- Dotnet-format.

Feat: Item lock

---

MapleServer2/PacketHandlers/Game/NewsNotificationHandler.cs
MapleServer2/Packets/NewsNotificationPacket.cs

Small PR for News Notification to function.
This still pulls info from the original site.

News Notification

---

MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
MapleServer2/PacketHandlers/Game/InteractObjectHandler.cs
MapleServer2/PacketHandlers/Game/QuestHandler.cs
MapleServer2/Packets/QuestPacket.cs
MapleServer2/Types/Player.cs
MapleServer2/Types/QuestStatus.cs

#62
- Added QuestStatus;
- Re-worked QuestHandler;
- Handling binoculars exploration quests;

Feat: Quests WIP

---

MapleServer2/PacketHandlers/Game/EmoteHandler.cs
MapleServer2/Packets/EmotePacket.cs

- Small PR to be able to use emote items to learn emotes

Learn Emotes

---

MapleServer2/PacketHandlers/Game/InteractObjectHandler.cs

- Missing packet to complete exploration goal.

Fix: Missing packet #194

---

GameDataParser/Hash/ms2-premium-club-daily-benefit-metadata-hash
GameDataParser/Hash/ms2-premium-club-package-metadata-hash
GameDataParser/Parsers/PremiumClubDailyBenefitParser.cs
GameDataParser/Parsers/PremiumClubPackageParser.cs
GameDataParser/Program.cs
Maple2Storage/Types/Metadata/PremiumClubDailyBenefitMetadata.cs
Maple2Storage/Types/Metadata/PremiumClubPackageMetadata.cs
MapleServer2/Data/Static/PremiumClubDailyBenefitMetadataStorage.cs
MapleServer2/Data/Static/PremiumClubPackageMetadataStorage.cs
MapleServer2/PacketHandlers/Game/InsigniaHandler.cs
MapleServer2/PacketHandlers/Game/PremiumClubHandler.cs
MapleServer2/Types/Player.cs

- Parsing Premium Club packages and daily items.
- Removed Player.isVIP to check on a player's PremiumClub status and using the player's premiumclub expiration instead

PremiumClub Parsing

---

MapleServer2/PacketHandlers/Game/MasteryHandler.cs
MapleServer2/PacketHandlers/Game/RequestItemUseMultipleHandler.cs
MapleServer2/Packets/FieldObjectPacket.cs
MapleServer2/Packets/InteractActorPacket.cs
MapleServer2/Servers/Game/FieldManager.cs
MapleServer2/Tools/InventoryController.cs
MapleServer2/Tools/SpawnGenerator.cs

- **InteractActorPacket**
- Only write extra int if `InteractActorType` is **Extractor** or **Gathering**;
- **FieldObjectPacket**
- Small fix on **LoadPlayer** packet;
- Added packet to remove player from map;
- **FieldManager**
- Added `FieldObjectPacket.RemovePlayer()`;
- **InventoryController**
- `Consume()` don't remove item if amount changed is greater than amount owned;
- Removed `Update()` function;
- Updated `MasteryHandler` and `RequestItemUseMultipleHandler` to use `Consume()`.
- **Dotnet-format**

Small fixes

---

MapleServer2/MapleServer2.csproj
MapleServer2/Servers/Game/FieldManager.cs
MapleServer2/Triggers/ArcadeTriggers.cs
MapleServer2/Triggers/CameraTriggers.cs
MapleServer2/Triggers/DungeonTriggers.cs
MapleServer2/Triggers/FieldObjectTriggers.cs
MapleServer2/Triggers/FieldPropertyTriggers.cs
MapleServer2/Triggers/MiniGameTriggers.cs
MapleServer2/Triggers/NpcTriggers.cs
MapleServer2/Triggers/PlayerTriggers.cs
MapleServer2/Triggers/TriggerConditions.cs
MapleServer2/Triggers/TriggerContext.cs
MapleServer2/Triggers/TriggerScript.cs
MapleServer2/Triggers/UITriggers.cs
MapleServer2/Triggers/WeddingTriggers.cs

Currently does nothing because mapName isn't parsed, but this should help anyone else who wants to begin implementing triggers get started.

Add skeleton code for handling triggers

---

MapleServer2/PacketHandlers/Game/ChangeAttributesHandler.cs
MapleServer2/Types/Item.cs
MapleServer2/Types/ItemStats.cs

Add check for two-handed weapons so their basic and bonus stats are doubled.
#237

Fix: Issue #237

---

MapleServer2/Database/DatabaseContext.cs
MapleServer2/Database/DatabaseManager.cs
MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
MapleServer2/PacketHandlers/Game/KeyTableHandler.cs
MapleServer2/Types/GameOptions.cs
MapleServer2/Types/Hotbar.cs
MapleServer2/Types/KeyBind.cs
MapleServer2/Types/Player.cs
MapleServer2/Types/QuickSlot.cs

- Implemented right click to add item/skill to quick slots.
- Saving quick slots and keybinds to database.
- Hotbar size changed to 22 slots.

Feat: Saving keybinds and quick slots

---

MapleServer2/Database/DatabaseContext.cs
MapleServer2/PacketHandlers/Game/PrestigeHandler.cs
MapleServer2/Packets/CharacterListPacket.cs
MapleServer2/Packets/PrestigePacket.cs
MapleServer2/Types/Player.cs

- Fixed correctly displaying item rarity on character tab;
- Saving to DB prestige reward claimed.

Fix: Item rarity & saving prestige reward

---

.gitignore
GameDataParser/Hash/ms2-animation-metadata-hash
GameDataParser/Parsers/AnimationParser.cs
GameDataParser/Program.cs
Maple2Storage/Types/Metadata/AnimationMetadata.cs
MapleServer2/Data/Static/AnimationStorage.cs
MapleServer2/PacketHandlers/Game/InsigniaHandler.cs
MapleServer2/Servers/Game/FieldManager.cs
MapleServer2/Types/Mob.cs

-Changed default animation of Mob Class to a Monster's walking animation, which has a different id for every monster and gets read from GetSequenceIdBySequenceName

Animation Parser and Storage

---

MapleServer2/Network/Session.cs

Fix: correctly disconnect player if client crashes

---

MapleServer2/Database/DatabaseContext.cs
MapleServer2/Database/DatabaseManager.cs
MapleServer2/PacketHandlers/Game/JobHandler.cs
MapleServer2/PacketHandlers/Game/SkillBookTreeHandler.cs
MapleServer2/Packets/DungeonWaitPacket.cs
MapleServer2/Packets/JobPacket.cs
MapleServer2/Packets/SkillBookTreePacket.cs
MapleServer2/Servers/Game/FieldManager.cs
MapleServer2/Tools/MobAIManager.cs
MapleServer2/Types/Mob.cs
MapleServer2/Types/Player.cs
MapleServer2/Types/SkillTab.cs

- #281 
- Implemented:
- Adding new build trees;
- Presets;
- Renaming builds;
- Saving to database.
- Reworked reseting skill trees;
Dotnet-format

Feat: SkillTabs (new tabs, reset, preset and database)

---

GameDataParser/Hash/ms2-skill-metadata-hash
GameDataParser/Parsers/SkillParser.cs
Maple2Storage/Types/Metadata/SkillMetadata.cs
MapleServer2/Packets/SkillDamagePacket.cs
MapleServer2/Servers/Game/FieldManager.cs
MapleServer2/Tools/GameCommandActions.cs
MapleServer2/Types/Player.cs
MapleServer2/Types/SkillCast.cs
MapleServer2/Types/Status.cs

- Parsing SubType and DurationTick on skills.
- Adding type `SkillAdditionalData` since this will have many more data to be add for status types, buff types, power ups on skills, splash effects, etc..
Open to suggestions 😊

Feat: Additional Data to Skills. Parsing DurationTick ✔

---

GameDataParser/Parsers/DungeonParser.cs
Maple2Storage/Tools/RandomProvider.cs
Maple2Storage/Types/DungeonMetadata.cs
MapleServer2/Data/Static/ItemMetadataStorage.cs
MapleServer2/Data/Static/MapEntityStorage.cs
MapleServer2/PacketHandlers/Game/BeautyHandler.cs
MapleServer2/PacketHandlers/Game/CardReverseGameHandler.cs
MapleServer2/PacketHandlers/Game/DungeonHandler.cs
MapleServer2/PacketHandlers/Game/FishingHandler.cs
MapleServer2/PacketHandlers/Game/Helpers/ItemUseHelper.cs
MapleServer2/PacketHandlers/Game/InteractObjectHandler.cs
MapleServer2/PacketHandlers/Game/MapleopolyHandler.cs
MapleServer2/PacketHandlers/Game/RequestItemUseHandler.cs
MapleServer2/PacketHandlers/Game/SkillHandler.cs
MapleServer2/PacketHandlers/Login/CharacterManagementHandler.cs
MapleServer2/Packets/SkillUsePacket.cs
MapleServer2/Servers/Login/LoginSession.cs
MapleServer2/Tools/MobAIManager.cs
MapleServer2/Triggers/FieldObjectTriggers.cs
MapleServer2/Types/DamageHandler.cs
MapleServer2/Types/DungeonSession.cs
MapleServer2/Types/Fishing.cs
MapleServer2/Types/ItemStats.cs
MapleServer2/Types/Mob.cs
MapleServer2/Types/MobAI.cs
MapleServer2/Types/MobSpawn.cs
MapleServer2/Types/Player.cs

Thread-safe provider for "Random" instances. ty @eotetb
Dotnet-format.
Fixing issues found by linter.

RandomProvider & Cleanup

---

MapleServer2/MapleServer.cs
MapleServer2/nlog.config

- Adding colors to each level of logger.
- Fix formatting.

Fix: Implementation of Logger in MapleServer2.cs

---

MapleServer2/Database/DatabaseContext.cs
MapleServer2/Database/DatabaseManager.cs
MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
MapleServer2/PacketHandlers/Game/GuildHandler.cs
MapleServer2/PacketHandlers/Game/QuestHandler.cs
MapleServer2/PacketHandlers/Login/CharacterManagementHandler.cs
MapleServer2/Types/Guild/Guild.cs
MapleServer2/Types/Guild/GuildMember.cs
MapleServer2/Types/Player.cs

- Fixed guild not being saved correctly to database;
- Fixed being able to complete multiple times the same quest;
- Removed delete rows from `DatabaseManager.DeleteCharacter()`, instead set `Player.IsDeleted = true`

Database fixes + Quest fixes

---

MapleServer2/PacketHandlers/Game/BeautyHandler.cs
MapleServer2/PacketHandlers/Game/EnterEventFieldHandler.cs
MapleServer2/PacketHandlers/Game/GuildHandler.cs
MapleServer2/PacketHandlers/Game/InstrumentHandler.cs
MapleServer2/PacketHandlers/Game/MoveFieldHandler.cs
MapleServer2/PacketHandlers/Game/RequestCubeHandler.cs
MapleServer2/PacketHandlers/Game/RequestHomeHandler.cs
MapleServer2/PacketHandlers/Game/RequestItemPickupHandler.cs
MapleServer2/PacketHandlers/Game/RideHandler.cs
MapleServer2/Servers/Game/FieldManager.cs
MapleServer2/Tools/HomeManager.cs
MapleServer2/Types/Home/Home.cs
MapleServer2/Types/Player.cs

- Fix #309 
- Fix #315 
- Fixed home templates not working correctly;
- Fixed newly created homes not having the correct instance;
- Fixed second rider of two person mounts not leaving the mount correctly;
- Beauty Salon/Dye Workshop/Plastic surgery are now instanced and the return portal works.

Various fixes

---

MapleServer2/Database/DatabaseManager.cs
MapleServer2/PacketHandlers/Login/LoginHandler.cs
MapleServer2/Packets/LoginResultPacket.cs

Fix: Don't create two accounts with the same username

Feat: Password authentication

---

MapleServer2/Commands/Game/GotoCommands.cs
MapleServer2/Commands/Game/InfoCommands.cs
MapleServer2/Commands/Game/UnlockCommands.cs
MapleServer2/PacketHandlers/Game/QuitHandler.cs
MapleServer2/PacketHandlers/Game/UserChatHandler.cs
MapleServer2/Servers/Game/FieldManager.cs
MapleServer2/Servers/Game/PlayerStorage.cs
MapleServer2/Tools/CommandManager.cs

- Three new commands. Online, unlock and trophy.
- Fix for `FieldManager`. It was releasing instances when it shouldn't.

Online, Unlock and trophy commands & Fix for instances

---

MapleServer2/Commands/Game/UnlockCommands.cs
MapleServer2/Database/Classes/DatabaseBanner.cs
MapleServer2/Database/Classes/DatabaseHotbar.cs
MapleServer2/Database/DatabaseTable.cs
MapleServer2/MapleServer.cs
MapleServer2/Tools/GuildManager.cs
MapleServer2/Tools/HomeManager.cs
MapleServer2/Triggers/MiniGameTriggers.cs

- Save players/guilds/homes to **database** on process exit;
- Formatting.

Save state on server exit

---

MapleServer2/Triggers/NpcTriggers.cs

Correctly spawn mob or npc entity.

Fix: create monster trigger function

---

MapleServer2/Database/Classes/DatabaseShop.cs

Return null if shop doesn't exists.

Fix: Database Shop

---

MapleServer2/Database/Classes/DatabaseAccount.cs
MapleServer2/Database/Classes/DatabaseBuddy.cs
MapleServer2/Database/Classes/DatabaseCharacter.cs
MapleServer2/Database/Classes/DatabaseGuildMember.cs
MapleServer2/Database/DatabaseManager.cs
MapleServer2/Database/SQL/Database.sql
MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
MapleServer2/PacketHandlers/Game/BuddyHandler.cs
MapleServer2/PacketHandlers/Game/QuitHandler.cs
MapleServer2/Packets/BuddyPacket.cs
MapleServer2/Servers/Game/GameSession.cs
MapleServer2/Tools/BuddyManager.cs
MapleServer2/Types/Buddy.cs
MapleServer2/Types/Player.cs

- Save buddies to database;
- Correctly handling login/logout notifications;
- Adding offline players;

Fix: Buddies

---

MapleServer2/PacketHandlers/Game/BeautyHandler.cs
MapleServer2/PacketHandlers/Game/GlobalPortalHandler.cs
MapleServer2/Types/Player.cs

- Fixed events return coord;
- Fixed entering events with mounts.

Fix: Events

---

MapleServer2/Database/Classes/DatabaseInventory.cs
MapleServer2/PacketHandlers/Game/CharacterInfoHandler.cs
MapleServer2/Packets/CharacterInfoPacket.cs
MapleServer2/Packets/CharacterListPacket.cs
MapleServer2/Packets/FieldPacket.cs

- Resolves #278 
- Fixes #357 
Implemented writing badge packet;
Implemented character info packet.

Feat: character info handler

---

MapleServer2/PacketHandlers/Game/ItemRepackageHandler.cs

Fix: master

---

MapleServer2/PacketHandlers/Game/FallDamageHandler.cs
MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs

- Fix an issue where it wasn't showing the UI of beauty with mounts

Fix: FallDamageHandler missing packet send

---

MapleServer2/PacketHandlers/Game/EnterEventFieldHandler.cs
MapleServer2/PacketHandlers/Game/GuildHandler.cs
MapleServer2/PacketHandlers/Game/MoveFieldHandler.cs
MapleServer2/PacketHandlers/Game/RequestHomeHandler.cs
MapleServer2/Types/Player.cs

Warp function is already handling if ReturnCoord should be set or not. 
Removed everywhere where ReturnCoord was being set.

Fix: ReturnCoord

---

GameDataParser/Program.cs
MapleServer2/Commands/Core/CommandBase.cs
MapleServer2/Commands/Core/CommandHelpers.cs
MapleServer2/Commands/Game/CurrencyCommands.cs
MapleServer2/Commands/Game/EntityCommands.cs
MapleServer2/Commands/Game/EventCommands.cs
MapleServer2/Commands/Game/GMCommands.cs
MapleServer2/Commands/Game/GotoCommands.cs
MapleServer2/Commands/Game/GuildCommands.cs
MapleServer2/Commands/Game/InfoCommands.cs
MapleServer2/Commands/Game/ItemCommands.cs
MapleServer2/Commands/Game/PlayerCommands.cs
MapleServer2/Commands/Game/QuestCommands.cs
MapleServer2/Commands/Game/UnlockCommands.cs
MapleServer2/Data/Static/SkillMetadataStorage.cs
MapleServer2/Managers/CommandManager.cs
MapleServer2/Network/Session.cs

- Added usage for each command;
- New command 'info' and 'startquest';

Commands rework

---

Maple2Storage/Types/GemSlot.cs
MapleServer2/Database/Classes/DatabaseInventory.cs
MapleServer2/Database/Classes/DatabaseItem.cs
MapleServer2/Database/SQL/Database.sql
MapleServer2/PacketHandlers/Game/RequestGemEquipmentHandler.cs
MapleServer2/Packets/CharacterListPacket.cs
MapleServer2/Packets/FieldPacket.cs
MapleServer2/Packets/GemPacket.cs
MapleServer2/Types/Inventory.cs
MapleServer2/Types/Item.cs

- Converted Badge Inventory to an array
- Fixed being able to unequip all badges
- Fixed transparency badge
- Fixed character picture in the bottom right

Badge fixes

---

MapleWebServer/Controllers/ProfilesController.cs

- Deleting all old image files for that character id folder;
- Added `DateTimeOffset.Now.ToUnixTimeSeconds()` to prevent caching in the client.

Fix: profile picture not updating correctly

---

MapleServer2/Types/Home/Home.cs

- Fix creating home with an empty template

Fix creating home

---

GameDataParser/Parsers/QuestParser.cs
MapleServer2/Managers/FieldManager.cs
MapleServer2/PacketHandlers/Game/Helpers/QuestHelper.cs
MapleServer2/PacketHandlers/Game/SkillHandler.cs

- Clean up on `FieldManager`;
- Fix `QuestHelper.UpdateQuest` to use target correctly.

Quest condition fix & Clean up

---

.github/workflows/dotnet.yml

Include dotnet-format checking

Action dotnetformat

---

MapleServer2/Database/Classes/DatabaseServer.cs
MapleServer2/Database/DatabaseManager.cs
MapleServer2/Database/SQL/Database.sql
MapleServer2/MapleServer.cs
MapleServer2/Tools/TaskScheduler.cs

- Added boiler plate code for scheduling daily reset;
- New table 'server' with one column 'last_daily_reset'.

Feat: Daily Reset Scheduler

---

MapleServer2/PacketHandlers/Game/InteractObjectHandler.cs
MapleServer2/Packets/InteractObjectPacket.cs

Missing use packet in **InteractObjectHandler**

Fix: Gathering

---

MapleServer2/Database/Classes/DatabaseItem.cs
MapleServer2/PacketHandlers/Game/MeretMarketHandler.cs
MapleServer2/PacketHandlers/Game/ShopHandler.cs
MapleServer2/PacketHandlers/Game/UserChatHandler.cs
MapleServer2/Packets/ItemLinkPacket.cs
MapleServer2/Packets/MeretMarketPacket.cs
MapleServer2/Packets/ShopPacket.cs

implemented
change of shop sell packet as it was creating an unnecessary item

feat: Item Linking

---

MapleServer2/PacketHandlers/Game/RequestTaxiHandler.cs

Fix: Fast Travel

---

Maple2Storage/Maple2Storage.csproj
MaplePacketLib2/MaplePacketLib2.csproj
MaplePacketLib2/Tools/MapleStream.cs
MapleServer2/MapleServer2.csproj
MapleWebServer/MapleWebServer.csproj

Fix: Server crash by overflow exception

---

MapleServer2/Managers/FieldManager.cs

- Send spawn effect (ID: 90000814) in FieldManager when adding a mob to field.

Fix: Enemy HUD

---

MapleServer2/PacketHandlers/Game/BlackMarketHandler.cs
MapleServer2/PacketHandlers/Game/RequestItemStorage.cs
MapleServer2/Packets/StorageInventoryPacket.cs
MapleServer2/Tools/InventoryController.cs
MapleServer2/Types/BankInventory.cs
MapleServer2/Types/Item.cs

Fix: Bank inventory

---

MapleServer2/MapleServer.cs
MapleServer2/Network/Server.cs
MapleServer2/Network/Session.cs
MapleServer2/PacketHandlers/Game/QuitHandler.cs
MapleServer2/PacketHandlers/Login/LoginHandler.cs
MapleServer2/Servers/Game/GameServer.cs
MapleServer2/Servers/Game/GameSession.cs
MapleServer2/Servers/Login/LoginServer.cs

- Properly remove player from field if errors occurred

Fix: Properly disconnect player

---

GameDataParser/Hash/ms2-constants-metadata-hash
GameDataParser/Parsers/BeautyParser.cs
GameDataParser/Parsers/ItemParser.cs
Maple2Storage/Enums/Gender.cs
Maple2Storage/Enums/TransferType.cs
Maple2Storage/Types/Metadata/BeautyMetadata.cs
Maple2Storage/Types/Metadata/ItemMetadata.cs
MapleServer2/Data/Static/BeautyMetadataStorage.cs
MapleServer2/Data/Static/ItemMetadataStorage.cs
MapleServer2/PacketHandlers/Game/Helpers/ItemBoxHelper.cs
MapleServer2/PacketHandlers/Game/RequestItemUseHandler.cs
MapleServer2/PacketHandlers/Login/CharacterManagementHandler.cs
MapleServer2/Packets/CharacterInfoPacket.cs
MapleServer2/Packets/CharacterListPacket.cs
MapleServer2/Types/Item.cs
MapleServer2/Types/Player.cs

- Added Gender enum
- New constants hash

Fix: open box with outfits

---

MapleServer2/Database/Classes/DatabaseCharacter.cs

Resolves #477 
Fixing mistake from #475

Fix: database

---

MapleServer2/Commands/Core/CommandTrigger.cs
MapleServer2/Commands/Core/InGameCommand.cs
MapleServer2/Commands/Game/HomeCommands/AlarmCommand.cs
MapleServer2/Commands/Game/HomeCommands/BallCommand.cs
MapleServer2/Commands/Game/HomeCommands/GravityCommand.cs
MapleServer2/Commands/Game/HomeCommands/RandomCommand.cs
MapleServer2/Commands/Game/HomeCommands/SurveyCommand.cs
MapleServer2/Enums/SystemNotice.cs
MapleServer2/Managers/CommandManager.cs
MapleServer2/Managers/FieldManager.cs
MapleServer2/PacketHandlers/Game/HomeActionHandler.cs
MapleServer2/Packets/FieldPropertyPacket.cs
MapleServer2/Packets/HomeActionPacket.cs
MapleServer2/Packets/NoticePacket.cs
MapleServer2/Types/GuideObject.cs
MapleServer2/Types/Home/Home.cs
MapleServer2/Types/Home/HomeSurvey.cs

- #73 
House commands:
- Survey
- HostBall
- Roll
- RandomUser
- HostGravity
- HostAlarm
Minor fixes to command system

Feat: House Commands

---

MapleServer2/Commands/Game/QuestCommands.cs
MapleServer2/Data/Static/QuestMetadataStorage.cs
MapleServer2/Database/Classes/DatabaseCharacter.cs
MapleServer2/Database/Classes/DatabaseQuest.cs
MapleServer2/Managers/ScriptManager.cs
MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
MapleServer2/PacketHandlers/Game/Helpers/QuestHelper.cs
MapleServer2/PacketHandlers/Game/InteractObjectHandler.cs
MapleServer2/PacketHandlers/Game/MasteryHandler.cs
MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
MapleServer2/PacketHandlers/Game/QuestHandler.cs
MapleServer2/Triggers/TriggerConditions.cs
MapleServer2/Types/Player.cs

Changed player's List of **QuestStatus** to Dictionary of id and **QuestStatus**;
Fixed finding available quests with no job requirement.

Fix: Quests

---

MapleServer2/Database/SQL/Database.sql
MapleServer2/Types/Player.cs

- Get account trophies before adding a new trophy on character creation.
- Set **AUTO_INCREMENT** of table ugc to `1000` to avoid issues with id 1. :)
- Formatting

Fix: Database & Character creation

---

MapleServer2/Types/Inventory.cs
MapleServer2/Types/Item.cs

Formatting and other suggestions by Rider

Fix: Sorting items past stack limit

---

MapleServer2/Data/Static/TrophyMetadataStorage.cs
MapleServer2/PacketHandlers/Game/FieldEnterHandler.cs
MapleServer2/Types/Player.cs
MapleServer2/Types/Trophy.cs

- Handling type "map" for trophies;
- Function IsInConditionRange made by @JamieDavidson
Co-Authored-By: JamieDavidson <JamieDavidson@users.noreply.github.com>

Fix: check for trophy range conditions

---

MapleServer2/Database/SQL/Database.sql

Add unique key to columns quest id and character id

Fix: add unique key to quests table

---

MapleServer2/Database/Classes/DatabaseCharacter.cs
MapleServer2/Database/Classes/DatabaseQuest.cs
MapleServer2/Database/DatabaseTable.cs
MapleServer2/PacketHandlers/Game/QuestHandler.cs
MapleServer2/PacketHandlers/Login/CharacterManagementHandler.cs
MapleServer2/Packets/MigrationPacket.cs
MapleServer2/Types/QuestStatus.cs

- Updating quests by UID instead of ID. 🤦 
- Formatting and suggestions.

Fix: updating quests

---

MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
MapleServer2/PacketHandlers/Game/FieldEnterHandler.cs
MapleServer2/PacketHandlers/Game/PrestigeHandler.cs
MapleServer2/PacketHandlers/Game/StatPointHandler.cs
MapleServer2/Packets/StatPacket.cs
MapleServer2/Packets/StatPointPacket.cs
MapleServer2/Types/Levels.cs
MapleServer2/Types/Player.cs
MapleServer2/Types/StatDistribution.cs
MapleServer2/Types/Stats.cs

Base stats on character creation;
Base stats for level up.
Fixed stat allocation;
Cleanup and formatting.

Feat: Base stats & Gain stats on level up

---

MapleServer2/Data/Static/MapMetadataStorage.cs
MapleServer2/PacketHandlers/Game/FishingHandler.cs
MapleServer2/Types/RegionSkillHandler.cs

- Fixed region skills that paint the ground, like priest's Sanctuary
- Don't add the effect on liquid.
- Match the height of the blocks correctly

Fix: Region skills

---

MapleServer2/PacketHandlers/Game/ChangeAttributesHandler.cs
MapleServer2/PacketHandlers/Game/InsigniaHandler.cs
MapleServer2/PacketHandlers/Game/ItemEnchantHandler.cs
MapleServer2/PacketHandlers/Game/ItemEquipHandler.cs
MapleServer2/PacketHandlers/Game/ItemExchangeHandler.cs
MapleServer2/PacketHandlers/Game/PrestigeHandler.cs
MapleServer2/PacketHandlers/Game/RequestGemEquipmentHandler.cs
MapleServer2/PacketHandlers/Game/RequestItemUseMultipleHandler.cs
MapleServer2/PacketHandlers/Game/RequestWorldMapHandler.cs
MapleServer2/PacketHandlers/Game/StateHandler.cs

Added LogUnknownMode to all handlers

---

MapleServer2/Packets/FieldNpcPacket.cs
MapleServer2/Packets/FieldPlayerPacket.cs
MapleServer2/Types/RegionSkillHandler.cs
MapleServer2/Types/SkillCast.cs

- Fix: #534 
- Fix: Packet structures

Fix: movement skills

---

.github/workflows/dotnet.yml

`dotnet format` is having issues with latest .NET version 6.0.200.
More info here:
https://github.com/dotnet/format/issues/1500

Change .NET SDK version to a fixed version

---

MapleServer2/Types/Inventory.cs
MapleServer2/Types/Player.cs

- Check if slot is already taken. Trying to find the reason as to why this issue happens.
- Formatting in Player.cs

Fix: Inventory

---

MapleServer2/Commands/Game/GMCommands.cs
MapleServer2/PacketHandlers/Game/JobHandler.cs
MapleServer2/PacketHandlers/Game/SkillBookTreeHandler.cs
MapleServer2/Types/Hotbar.cs
MapleServer2/Types/Player.cs
MapleServer2/Types/SkillTab.cs

Checking for job code when adding default skills.

Fix: default skills

---

MapleServer2/Managers/TrophyManager.cs
MapleServer2/PacketHandlers/Game/FallDamageHandler.cs

2 more trophies down, only hundreds to go!
Not 100% sure of the logic here... should Icarus only award progress if player has taken fall damage? Right now falling any more than 1m awards 1m worth of progress.

Add falling related trophies "Icarus" and "Living off the Edge"

---

MapleServer2/Managers/QuestManager.cs
MapleServer2/Managers/TrophyManager.cs
MapleServer2/Tools/ConditionHelper.cs

Extracting helper functions to its own helper class.

Cleanup: QuestManager & TrophyManager

---

MapleServer2/PacketHandlers/Game/RequestItemUseHandler.cs
MapleServer2/Packets/NoticePacket.cs

yay
**Notes:**
- Confirm the colour palette being used for the RNG colours.
- Need to change the length + females locks similar to the preview image of the gender voucher.

Feat: Gender Voucher

---

GameDataParser/Parsers/FieldWarParser.cs

Invert null check in FieldWarParser

---

MapleServer2/MapleServer.cs
MapleServer2/Network/Session.cs
MapleWebServer/Program.cs

- MapleWebServer: Removed padding and only logging information+.
- MapleServer2: Removed padding, changed color theme, only logging information+ to file.
- Added colors back to RECV and SEND debug packets

Minor: refine logging

---

MapleServer2/Database/Classes/DatabaseGuild.cs
MapleServer2/Database/SQL/Database.sql
MapleServer2/PacketHandlers/Game/UgcHandler.cs
MapleServer2/Packets/GuildPacket.cs
MapleServer2/Packets/UgcPacket.cs
MapleServer2/Triggers/FieldObjectTriggers.cs
MapleServer2/Types/Ugc.cs
MapleWebServer/Endpoints/GuildEmblemEndpoint.cs
MapleWebServer/Endpoints/UploadEndpoint.cs
MapleWebServer/Enums/PostUgcMode.cs
MapleWebServer/Program.cs

- #386 
- Implemented UGC Emblems for guilds;
- Also added logging to an crash in queenstown related to triggers.

Feat: Guild Emblems

---

MapleServer2/PacketHandlers/Game/ChangeAttributesHandler.cs
MapleServer2/PacketHandlers/Game/EnchantScrollHandler.cs
MapleServer2/PacketHandlers/Game/Helpers/EnchantHelper.cs
MapleServer2/PacketHandlers/Game/Helpers/ItemSocketScrollHelper.cs
MapleServer2/PacketHandlers/Game/Helpers/MailHelper.cs
MapleServer2/PacketHandlers/Game/ItemEnchantHandler.cs
MapleServer2/PacketHandlers/Game/ItemSocketSystemHandler.cs
MapleServer2/PacketHandlers/Game/LimitBreakHandler.cs
MapleServer2/PacketHandlers/Game/MeretMarketHandler.cs
MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
MapleServer2/PacketHandlers/Game/RequestItemUseHandler.cs
MapleServer2/PacketHandlers/Game/RequestTaxiHandler.cs
MapleServer2/Tools/ScriptLoader.cs
MapleServer2/Types/Item.cs
MapleServer2/Types/ItemStats/ConstantStats.cs
MapleServer2/Types/ItemStats/ItemStats.cs
MapleServer2/Types/ItemStats/StaticStats.cs

- Cache scripts for better performance

Rework: ScriptLoader

---

MapleServer2.sln.DotSettings
MapleServer2/Managers/Actors/Character.cs
MapleServer2/Managers/Actors/FieldActor.cs
MapleServer2/Managers/Actors/FieldObject.cs
MapleServer2/Managers/Actors/Mob.cs
MapleServer2/Managers/Actors/Npc.cs
MapleServer2/Managers/FieldManager.cs
MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
MapleServer2/Triggers/PlayerTriggers.cs
MapleServer2/Types/FieldState.cs
MapleServer2/Types/HealingSpot.cs
MapleServer2/Types/Player.cs

- Changed **FieldActors** to be public instead of `private partial`;
- Some minor logic changes to **FieldManager** like using LINQ to check for null objects.

Rework: FieldActors

---

MapleServer2/MapleServer2.csproj

Bump Maple2.PathEngine version

Fix: Server crashing

---

MapleServer2/PacketHandlers/Game/BeautyHandler.cs

Fix: Update Modifying Existing Face Decoration

---

MapleServer2/Commands/Game/InfoCommands.cs

Fix: /find command

---

MapleServer2/PacketHandlers/Game/FishingHandler.cs

Fix: FishingHandler

---

MapleServer2/PacketHandlers/Login/LoginHandler.cs
MapleServer2/Servers/Game/GameServer.cs
MapleServer2/Servers/Login/LoginServer.cs
MapleServer2/Tools/ScriptLoader.cs

- Remove sessions not connected;
- Change logging for Script not found to `Information`;
- Check for null player on LoginHandler.

Fix: Login NullException

---

MapleServer2/Packets/StatPointPacket.cs

Fix: Stat allocation

---

MapleServer2/Database/Classes/DatabaseAuthData.cs
MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
MapleServer2/PacketHandlers/Login/LoginHandler.cs
MapleServer2/Packets/LoginResultPacket.cs
MapleServer2/Servers/Game/GameSession.cs

- Added a function for custom message box for login.

Stop connection directly to game server

---

Maple2Storage/Types/Coord.cs
MapleServer2/Managers/Actors/Character.cs
MapleServer2/Managers/Actors/FieldActor.cs
MapleServer2/Managers/Actors/Mob.cs
MapleServer2/Managers/Actors/Npc.cs
MapleServer2/Managers/FieldManager.cs
MapleServer2/MapleServer.cs
MapleServer2/Types/FieldNavigator.cs
MapleServer2/Types/IFieldActor.cs
MapleServer2/Types/Player.cs

- Fixed mob velocity and coord for packet **ControlMob**;
- Animations and AI is still kinda broken; (I will fix in future PR 🙏 )
- Fixed **PathEngine Error Handler** getting garbage collected;

Fix: Mob movement

---

MapleServer2/PacketHandlers/Game/BeautyHandler.cs

Fix: eye recolouring 

---

MaplePacketLib2/Crypto/MapleCipher.cs
MapleServer2/Network/Session.cs

- Stop ping bots from raising fatal exceptions because of wrong headers.

Minor: No more useless fatal exceptions

---

MapleServer2/Types/Inventory.cs

Fix: sorting

---

MapleServer2/Commands/Game/QuestCommands.cs
MapleServer2/Database/Classes/DatabaseQuest.cs
MapleServer2/Database/SQL/Database.sql
MapleServer2/Managers/Actors/Npc.cs
MapleServer2/Managers/FieldManager.cs
MapleServer2/PacketHandlers/Game/QuestHandler.cs
MapleServer2/Packets/FieldPropertyPacket.cs
MapleServer2/Packets/QuestPacket.cs
MapleServer2/Triggers/FieldPropertyTriggers.cs
MapleServer2/Triggers/NpcTriggers.cs
MapleServer2/Types/IFieldActor.cs
MapleServer2/Types/QuestStatus.cs

- Fix: quest packet
- Fixed a bunch of triggers related to npcs
Assassin tutorial should be 100% finished (??)

Fix: Assassin tutorial

---

MapleServer2/Constants/SendOp.cs
MapleServer2/Managers/Actors/FieldActor.cs
MapleServer2/Managers/Actors/Npc.cs
MapleServer2/Managers/FieldManager.cs
MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
MapleServer2/Packets/ChangeBackgroundPacket.cs
MapleServer2/Servers/Game/GameSession.cs
MapleServer2/Triggers/FieldObjectTriggers.cs
MapleServer2/Triggers/FieldPropertyTriggers.cs
MapleServer2/Triggers/MiniGameTriggers.cs
MapleServer2/Triggers/NpcTriggers.cs
MapleServer2/Triggers/TriggerConditions.cs
MapleServer2/Types/FieldNavigator.cs
MapleServer2/Types/IFieldActor.cs
MapleServer2/Types/Player.cs

- #508 
- Named OPCode 0x0100 as ChangeBackground;
- Fixed some animation issues with NPCs;
- Fixed npcs spawning floating in some places;
- Remove player from field on **Warp** instead of **FieldEnter**.

Fix: priest tutorial

---

.editorconfig

- Removed un supported configs
- Removed multiple override of values

Cleanup .editorconfig

---

Maple2Storage/Scripts/Npcs/11000508.lua
Maple2Storage/Scripts/Npcs/11000510.lua
MapleServer2/PacketHandlers/Game/Helpers/EnchantHelper.cs
MapleServer2/PacketHandlers/Game/ItemEnchantHandler.cs

- Fix event id for ophelia/peachy. (It was my fault, oops)
- Fix: null exception

Fix: enchanting

---

MapleServer2/Managers/DungeonManager.cs
MapleServer2/PacketHandlers/Game/DungeonHandler.cs
MapleServer2/PacketHandlers/Game/MoveFieldHandler.cs
MapleServer2/Servers/Game/GameSession.cs

there were some bugs in removing a dungeon session from the DungeonSessionList.

fix: dungeon system bug

---

MapleServer2/PacketHandlers/Game/FieldEnterHandler.cs
MapleServer2/Packets/JobPacket.cs
MapleServer2/Packets/SkillPointPacket.cs
MapleServer2/Packets/StatPointPacket.cs

Fix: skill tree

---

MapleServer2/Managers/Actors/Npc.cs
MapleServer2/Managers/DungeonManager.cs
MapleServer2/Managers/FieldManager.cs
MapleServer2/PacketHandlers/Common/QuitHandler.cs
MapleServer2/PacketHandlers/Game/Helpers/GatheringHelper.cs
MapleServer2/PacketHandlers/Game/InteractObjectHandler.cs
MapleServer2/PacketHandlers/Game/RequestItemPickupHandler.cs
MapleServer2/PacketHandlers/Game/RequestMoneyPickupHandler.cs
MapleServer2/PacketHandlers/Game/RideHandler.cs
MapleServer2/Packets/FieldItemPacket.cs
MapleServer2/Servers/Game/GameContainerConfig.cs
MapleServer2/Servers/Game/GameSession.cs
MapleServer2/Tools/FieldManagerFactory.cs
MapleServer2/Tools/TaskScheduler.cs
MapleServer2/Triggers/PlayerTriggers.cs
MapleServer2/Triggers/TriggerConditions.cs
MapleServer2/Types/FieldState.cs
MapleServer2/Types/Home/HomeSurvey.cs
MapleServer2/Types/Inventory.cs
MapleServer2/Types/Item.cs
MapleServer2/Types/Player.cs
MapleServer2/Types/RegionSkillHandler.cs
MapleServer2/Types/UGCBanner.cs

- FieldManager no longer disposes if all players left.
- It'll enter a "freeze" state where all loops are stopped.
- Items dropped now fade out after 3 minutes.
- Fixed a bug with UGC Banner Loop. Thanks Santi

Rework FieldManager

---

MapleServer2/Types/DismantleInventory.cs
MapleServer2/Types/Item.cs

Fix: Mistake in #673

---

MapleServer2/Types/DismantleInventory.cs

Fix: Mass Dismantle

---

MapleServer2/Database/Classes/DatabaseCharacter.cs
MapleServer2/PacketHandlers/Game/DungeonHandler.cs
MapleServer2/PacketHandlers/Game/HomeDoctorHandler.cs
MapleServer2/PacketHandlers/Game/RequestItemStorage.cs
MapleServer2/PacketHandlers/Game/SuperChatHandler.cs
MapleServer2/PacketHandlers/Game/UserChatHandler.cs
MapleServer2/Packets/CharacterListPacket.cs
MapleServer2/Packets/ChatPacket.cs
MapleServer2/Packets/DungeonHelperPacket.cs
MapleServer2/Packets/PartyPacket.cs
MapleServer2/Types/Player.cs

for dungeon assist, home storage, and home doctor

Player Access timers

---

MapleServer2/Commands/Game/GotoCommands.cs
MapleServer2/PacketHandlers/Game/MoveFieldHandler.cs
MapleServer2/PacketHandlers/Game/RequestCubeHandler.cs
MapleServer2/PacketHandlers/Game/RideHandler.cs
MapleServer2/PacketHandlers/Game/UserSyncHandler.cs
MapleServer2/Triggers/PlayerTriggers.cs
MapleServer2/Types/NpcTalk.cs
MapleServer2/Types/Player.cs

Fix: moving to same map with warp

---

MapleServer2/Managers/FieldManager.cs

Map objects will be able to be broken again.

Fix: Breakable Actor Object

---

MapleServer2/Commands/Game/GotoCommands.cs
MapleServer2/Types/Player.cs

- Fix: #350
- Fix: warping with /m and /goto when in a different channel

Fix: use game to game for tutorial maps

---

MapleServer2/Commands/Game/GotoCommands.cs
MapleServer2/Database/Classes/DatabaseCharacter.cs
MapleServer2/Managers/FieldManager.cs
MapleServer2/PacketHandlers/Game/FieldEnterHandler.cs
MapleServer2/Packets/FieldPlayerPacket.cs

- Fix: #407 (OMG! Thanks to Sky @0x4808D for finding out how to fix this simple and yet long standing issue and @kOchirasu for the code snippet)
- Fix: teleporting to another player;
- Added some pet related data to FieldPlayerPacket;
- Fixed spawning and removing pets for other players.

Fix: mob health bars

---

MapleServer2/Packets/BuffPacket.cs
MapleServer2/Packets/FieldPlayerPacket.cs
MapleServer2/Types/AdditionalEffects.cs
MapleServer2/Types/Player.cs

changed FieldPlayerPacket to send buffs instead of passive skills

additional effect goodies

---

MapleServer2/Database/Classes/DatabaseEvent.cs
MapleServer2/Database/Seeding/EventsSeeding.sql
MapleServer2/Database/Types/GameEvent.cs
MapleServer2/Packets/GameEventPacket.cs

Adds the Game Event "TrafficOptimizer"
This makes it so you can adjust how often user sync packets are sent to the server. Currently set as 300ms (same as KMS2)

Traffic Optimizer

---

GameDataParser/GameDataParser.csproj
GameDataParser/Parsers/MapParser.cs

Bump Maple2.File

---

MapleServer2/Constants/Constant.cs
MapleServer2/Network/Session.cs
MapleServer2/PacketHandlers/Common/QuitHandler.cs
MapleServer2/PacketHandlers/Login/CharacterManagementHandler.cs
MapleServer2/PacketHandlers/Login/LoginHandler.cs
MapleServer2/PacketHandlers/Login/ServerEnterPacketHandler.cs
MapleServer2/Types/DamageHandler.cs
MapleServer2/Types/Player.cs

- Changed server IP routing to point to localhost when the incoming connection is from localhost (some networks aren't configured to do this properly and will drop connection attempts)
- Reduced damage for cross class damage sources like red & blue lapenshards by half
- Fixed an issue where dot damage additional effects with no source would throw an exception
- Fixed an issue where attacking with no weapon in hand would throw an exception

localhost specialized routing & bug fixes

---

MapleServer2/Managers/QuestManager.cs
MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
MapleServer2/Triggers/PlayerTriggers.cs

- #508 
- Related to soul binder tutorial

More triggers

---

Maple2Storage/Scripts/Npcs/11000215.lua
Maple2Storage/Scripts/Npcs/11000254.lua
MapleServer2/Managers/Actors/Character.cs
MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
MapleServer2/Types/NpcTalk.cs

Fix combat stance and npc scripts

---

Maple2Storage/Scripts/Npcs/11001257.lua
MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs

Checks for the correct quest in order to teleport out
Added a check for talk script type if it's a job script in order to add the dialog type flag.

Fix: Moren NPC in Runeblader Tutorial

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature-missing.md

Use issue templates

---

MapleServer2/Managers/Actors/Npc.cs
MapleServer2/Managers/FieldManager.cs
MapleServer2/Types/FieldNavigator.cs

Some nullables fixes for FieldNavigator and FieldManager
- Fix: #760

Fix: Check if navmesh exists

---

MapleServer2/Commands/Game/GMCommands.cs

SetUserValue Command for Triggers

---

MapleServer2/Commands/Core/GameCommandTrigger.cs
MapleServer2/Commands/Game/HomeCommands/RandomCommand.cs
MapleServer2/PacketHandlers/Game/UserChatHandler.cs

Show error on roll command

---

MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
MapleServer2/PacketHandlers/Game/QuestHandler.cs
MapleServer2/Types/QuestStatus.cs

Fix: Reputation NPC talk edgecase

---

MapleServer2/Database/Classes/DatabaseBeautyShopItem.cs

Fix: Include Gender Neutral Items in Beauty Shop

---

MapleServer2/PacketHandlers/Game/WardrobeHandler.cs

Fix: Wardrobe removing hair/eyes/makeup

---

MapleServer2/Database/Classes/DatabaseAccount.cs
MapleServer2/Database/Classes/DatabaseCharacter.cs
MapleServer2/Database/SQL/Database.sql
MapleServer2/MapleServer.cs
MapleServer2/PacketHandlers/Game/FieldEnterHandler.cs
MapleServer2/PacketHandlers/Game/PremiumClubHandler.cs
MapleServer2/Packets/PremiumClubPacket.cs
MapleServer2/Types/Account.cs

Fix: Premium Club Item Claiming

---

MapleServer2/PacketHandlers/Game/TradeHandler.cs

Fix: Trade duplication

---

MapleServer2/Managers/FieldManager.cs
MapleServer2/Types/ConditionSkillTarget.cs
MapleServer2/Types/RegionSkillHandler.cs

Added null checks
- Fix: #795 
- Fix: #789

Fix: skill region handler

---

MapleServer2/Database/Classes/DatabaseBankInventory.cs
MapleServer2/Database/Classes/DatabaseCharacter.cs
MapleServer2/PacketHandlers/Game/ItemStorageHandler.cs
MapleServer2/Types/BankInventory.cs

Fix: Add Session to BankInventory's Currency

---

MapleServer2/Triggers/FieldObjectTriggers.cs
MapleServer2/Types/Gemstone.cs
MapleServer2/Types/Inventory.cs

Fix: nullables

---

MapleServer2/Managers/PartyManager.cs
MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
MapleServer2/PacketHandlers/Game/ClubHandler.cs
MapleServer2/PacketHandlers/Game/FieldEnterHandler.cs
MapleServer2/PacketHandlers/Game/MatchPartyHandler.cs
MapleServer2/PacketHandlers/Game/PartyHandler.cs
MapleServer2/Packets/PartyPacket.cs
MapleServer2/Types/Party.cs
MapleServer2/Types/Player.cs

- Fixes reconnecting / warping appearing offline
- Fixes party leader turnover logic
- Fixes party members not leaving correctly
- Fixes not being able to kick offline members
- Fixes party packet structure being incorrect in some places
TODO:
- fix regen bug (spams the UpdateHitpoints packet)
#787 
[.](https://www.youtube.com/watch?v=jDBPmEAheCY)

Fix: Parties

---

GameDataParser/Parsers/QuestParser.cs
Maple2Storage/Types/Metadata/QuestMetadata.cs
MapleServer2/PacketHandlers/Game/QuestHandler.cs
MapleServer2/Types/QuestStatus.cs

Hello, I discovered this project today and encountered problems proceeding as the Strike class, because I need the red herbs given upon accepting the Chairwoman Jayce quest.

Implementing item rewards upon accepting quests.
