AlanMorel/MapleServer2

MapleServer2/PacketHandlers/Game/FieldEnterHandler.cs
MapleServer2/PacketHandlers/Game/StatPointHandler.cs
MapleServer2/Packets/StatPointPacket.cs
MapleServer2/Types/Player.cs
MapleServer2/Types/StatDistribution.cs

---
Catches packets (RecvOp code 0x009A) requesting an increment in a stat value (ie +1 to Strength, Dex, Luck, Int, Health, or Crit Rate)
* Packet format: `<mode byte> <stat index>`
* Example packet: `02 00` (translated: increment the strength stat)
* Mode byte - `02` represents the increment command
* Mode byte - `03` represents the reset stat distribution command
* Stat index - the indices represented by this byte include   
* Strength - `00`
* Dex - `01`
* Int - `02`
* Luck - `03`
* Health - `04`
* Crit Rate - `0x11` (17 in decimal form)
Generates a packet (SendOp code 0x0046) in response to a request for StatPoints. 
Contains the following modes:
* Mode byte - `00` requests the total stat points a player has
* Mode byte - `01` requests the player's stat distribution
Consists of the …

Stat points increment and reset: implementation

---

MaplePacketLib2/Tools/PacketReader.cs
MaplePacketLib2/Tools/PacketWriter.cs

These two basic types were missing, theres also En/DecodeCoords and En/Decode2ftXX functions missing, but generally speaking those could be added through usage of ReadFloat and WriteFloat.

Added ReadFloat and WriteFloat

---

MapleServer2/PacketHandlers/Game/GuildHandler.cs
MapleServer2/Packets/GuildPacket.cs
MapleServer2/Tools/GuildManager.cs
MapleServer2/Types/Guild.cs

Added:
- Guild inviting
- Kicking
- Re-assigning leader
- Leaving (ish)
- Member mottos/messages
Leaving is sort of broken at the moment because of a bigger issue - Guild Ids are not being stored in a players information, so there is a mismatch on Ids until that is fixed.. somehow 
#83

Guild invites, kick, leadership transfer, , leaving (sort of), member mottos

---

MapleServer2/PacketHandlers/Game/FieldEnterHandler.cs
MapleServer2/PacketHandlers/Game/ItemEquipHandler.cs
MapleServer2/PacketHandlers/Game/SkillHandler.cs
MapleServer2/Packets/FieldObjectPacket.cs
MapleServer2/Packets/FieldPacket.cs
MapleServer2/Packets/SkillDamagePacket.cs
MapleServer2/Packets/SkillUsePacket.cs
MapleServer2/Packets/StatPacket.cs
MapleServer2/Packets/UserBattlePacket.cs
MapleServer2/Servers/Game/FieldManager.cs
MapleServer2/Tools/GameCommandActions.cs
MapleServer2/Types/Mob.cs
MapleServer2/Types/Npc.cs
MapleServer2/Types/Player.cs

- Passing a list of mobs from the field to the SkillDamagePacket
- Adding `AddMob, LoadMob & ControlMob` to be use for the Mob class
- Adding `ApplyHeal` to the Packet
- Adding `MobSkillUse` to the Packet
- Adding `StatPacket` into the proper Packet class
- Adding `mob` calling on `GameCommandAction`
- Adding spawing mobs to into the state of the field.
- Minor other fix

Separating Mob from Npc, Handle Damage & Stat for Mobs

---

GameDataParser/Program.cs
MapleServer2/MapleServer.cs

`type.Parse()` uses OS globalization to determine whether to use `,` or `.` for decimal points, this change forces it to use `.` for decimal points.

Fix: force en-US globalization

---

GameDataParser/Files/Export/GuildMetadataExport.cs
GameDataParser/Parsers/GuildParser.cs
GameDataParser/Program.cs
Maple2Storage/Types/Metadata/GuildMetadata.cs
MapleServer2/Data/Static/GuildMetadataStorage.cs
MapleServer2/PacketHandlers/Game/FieldEnterHandler.cs
MapleServer2/PacketHandlers/Game/GuildHandler.cs
MapleServer2/Packets/GuildPacket.cs
MapleServer2/Types/Guild.cs
MapleServer2/Types/Player.cs

Parsing some data for guild contributions and buffs. Submitting this to see if I'm doing it correctly before diving deeper.
Buffs are a bit odd. both personal and guild buffs are in the same table. Personal buffs take meso to use while guild buffs take guild funds. I'm differentiating them by just the id number.
At the moment if you're trying to use a buff, you'll get an error because there's multiple entries of the same buff (due to levels). I'll probably need assistance on how to properly implement guild buffs and their levels. And also calling out the correct buff and level from the parsed data.
Oh, also, I forgot to push out the fieldhandler update from my last PR so stickers can load, so there's that.

Guild data parsing and other fixes

---

MapleServer2/PacketHandlers/Game/ItemEquipHandler.cs
MapleServer2/PacketHandlers/Game/StatPointHandler.cs
MapleServer2/Packets/FieldPacket.cs
MapleServer2/Packets/PartyPacket.cs
MapleServer2/Packets/StatPacket.cs
MapleServer2/Types/Player.cs
MapleServer2/Types/PlayerStats.cs

Includes a working implementation of player stats and stat point allocation; includes a basic rewrite of `PlayerStats`.
- Rewrite `PlayerStats` struct to a class.
- Mimics order and behavior using the non-generic `OrderedDictionary`.
- Includes stat Increase, Decrease methods, used to apply stat bonuses (e.g. gear).
- Includes stat IncreaseBase, DecreaseBase methods, used to increase base stats.
- Uses a `StatDistribution` to account for allocated points (at the moment).
- Removes `CurrentHp` (use Hp, instead).
- Adds enum `PlayerStatId` to reference player stats.
- Add server packet to update player's stats in a field in `StatPacket.cs`.
- Add logic to update player's stats on stat allocation in `StatPointHandler.cs`.

Feat: Stat allocation/updates + Cleanup: PlayerStats

---

MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
MapleServer2/PacketHandlers/Game/ItemEquipHandler.cs
MapleServer2/PacketHandlers/Game/StatPointHandler.cs
MapleServer2/Packets/PartyPacket.cs
MapleServer2/Packets/StatPacket.cs
MapleServer2/Types/PlayerStats.cs

Includes a more robust PlayerStats implementation. Further stats identified including Stamina's stats and Hp/Sp/Sta regen times in milliseconds (ms).
- Stats sent on login.
- PlayerStats
- New constructor to assign base stat attribute distributions.
- `HpRegenTime` identified in milliseconds.
- `SpRegenTime` identified in milliseconds.
- `Stamina`, `StaRegen`, `StaRegenTime` correctly identified.
- 20 Stamina = 1 Block in-game
- `Increase`/`Decrease` methods used for temporary changes or effects.
- `IncreaseMax`/`DecreaseMax` methods used for stat bonuses (e.g. gear).
- On decrease, current Health/Spirit stay unaffected or capped to max value.
- `IncreaseBase`/`DecreaseBase` methods used for permanent stat bonuses (attributes).
- `InitializePool` method initializes Hp/Sp/Stamina with …

Feat: Add more robust PlayerStats

---

MapleServer2/PacketHandlers/Game/SkillHandler.cs
MapleServer2/Types/Player.cs
MapleServer2/Types/SkillCast.cs

Basic implementation of HP/SP/Stamina consumption + regeneration. Consuming a stat means decreasing the stat **temporarily**. 
- Skills consume SP now. 😢
- Skills only activate when enough SP is available.
- Player
- `ConsumeHp` for consuming health (e.g. damage).
- `ConsumeSp` for consuming spirit (e.g. skill use).
- `ConsumeStamina` for consuming stamina (e.g. mount dashing).
- SkillCast
- `GetCost` method for getting SP cost from skills metadata

Feat: Add HP/SP/Stamina regen + skill SP consumption.

---

MapleServer2/PacketHandlers/Game/ShopHandler.cs

Fixed issue #198 where item stacks for shops didn't multiple with amount purchased.
Confirmed in-client that it is now working.

Fix: #198 (Shops - Item stacks do not multiply with amount purchased)

---

GameDataParser/Parsers/ItemStatsParser.cs
GameDataParser/Parsers/QuestParser.cs
GameDataParser/Parsers/ScriptParser.cs

This should cover every ternary operator together with #210

fix: Explicit casting for ternary operators

---

MapleServer2/Enums/PartyNotice.cs
MapleServer2/PacketHandlers/Game/DungeonHandler.cs
MapleServer2/PacketHandlers/Game/MatchPartyHandler.cs
MapleServer2/PacketHandlers/Game/PartyHandler.cs
MapleServer2/Packets/CharacterListPacket.cs
MapleServer2/Packets/DungeonHelperPacket.cs
MapleServer2/Packets/DungeonPacket.cs
MapleServer2/Packets/MatchPartyPacket.cs
MapleServer2/Packets/PartyPacket.cs
MapleServer2/Tools/PartyManager.cs
MapleServer2/Types/Party.cs

The biggest changes to parties are the following four points:
1. Writing HP of the player in the WriteCharacter packet. This solves needing to send unnecessary packets to the player upon first joining a party.
2. Implement the ability to request to join a party if a party exists.
3. Above all else, when you invite players to a new party or by making a recruitment listing, the server makes a party in order for the other player(s) to join. We're treating a party of 1 as if the player is _not_ in a party. This allows players to invite others to a party if they've already established a 1 player party (i.e. if player a invites player b to a new party, but player c invites player a).
4. Implemented `PartyNotice` for the various different errors parties come across.
Party kicking and party …

Party fixes

---

GameDataParser/Parsers/NpcParser.cs
Maple2Storage/Types/NpcStats.cs

This PR proposes just a minor change that I almost overlooked when understanding the parsers. An `atp` tag indicates `Accuracy` instead of `Attack`, in the same way it is proposed by `ItemOptionRangeParser`.
Additionally, I have checked some of the values in the parsed output and they indeed correspond to the accuracy attribute, e.g., [slime](https://maplestory2.fandom.com/wiki/Slime) has 80 acc instead of 80 atk.

Fix: Attack on npcStats should be Accuracy.

---

MapleServer2/Data/Static/MapEntityStorage.cs
MapleServer2/PacketHandlers/Game/BeautyHandler.cs
MapleServer2/PacketHandlers/Game/MoveFieldHandler.cs
MapleServer2/Packets/CharacterListPacket.cs
MapleServer2/Types/Player.cs

Allows for safe returning in maps that do not have return exit portals
In most, if not all, cases, this is used for instance map teleporting - Beauty shops, housing, dungeon lobbies, etc.

Safe Return Teleporting

---

MapleServer2/PacketHandlers/Common/RequestTimeSyncHandler.cs
MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
MapleServer2/PacketHandlers/Common/ResponseVersionHandler.cs
MapleServer2/PacketHandlers/Game/ClientTickSyncHandler.cs
MapleServer2/PacketHandlers/Game/InstrumentHandler.cs
MapleServer2/PacketHandlers/Game/UserSyncHandler.cs
MapleServer2/Packets/InstrumentPacket.cs
MapleServer2/Packets/TimeSyncPacket.cs
MapleServer2/Servers/Game/FieldManager.cs
MapleServer2/Servers/Game/GameServer.cs
MapleServer2/Servers/Game/GameSession.cs
MapleServer2/Types/FieldState.cs
MapleServer2/Types/Instrument.cs
MapleServer2/Types/Player.cs

- Created an `Instrument` class for handling instruments in a given field.
- Added `Instrument` to `FieldState` in order to have instruments be playing if a player enters a map mid-play.
- Ensembles now work because session server tick changes were made:
- a Player session is now properly having their ServerTick be set. Before, we were setting it with client tick.
- Normally, the client is supposed to request the ServerTick every 1 second from the server. It's not doing it (we're probably missing some packet or something). As a current workaround, I'm updating a session's ServerTick via `UserSyncHandler`
- Added the default Emotes to the Player constructor

Instrument Ensemble & Tick Changes

---

.env.example
MapleServer2.sln
MapleServer2/Database/DatabaseContext.cs
MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
MapleServer2/PacketHandlers/Game/QuitHandler.cs
MapleServer2/PacketHandlers/Login/CharacterManagementHandler.cs
MapleServer2/PacketHandlers/Login/LoginHandler.cs
MapleServer2/PacketHandlers/Login/ServerEnterPacketHandler.cs
MapleServer2/Servers/Game/GameServer.cs
MapleServer2/Servers/Login/LoginServer.cs
MapleServer2/Tools/Dotenv.cs

- Split database info and added port;
- Added server IP, game and login port and server name to .env.
- Fixed `NpcTalkHandler` to not crash if NPC doesn't have script;
- Removed references of `Ms2Database` from `MapleServer2.sln`

Fix: Add IP and ports to .env file

---

MapleServer2/Constants/SendOp.cs
MapleServer2/MapleServer.cs
MapleServer2/PacketHandlers/Game/DungeonHandler.cs
MapleServer2/Packets/DungeonWaitPacket.cs
MapleServer2/Packets/TriggerPacket.cs
MapleServer2/Servers/Game/FieldManager.cs
MapleServer2/Servers/Game/GameSession.cs

Broadcast all packets to players on Field once
It creates the display in the dungeon which says what kind of dungeon it is and for how many players it was created
Added DungeonHandler Enum Type for entering dungeon lobby. This packet can / will probably be used to initiate trigger scripts
Added Check for send manual packet function, to prevent crashes on the server.

Changed Field Packet Updates

---

MapleServer2/PacketHandlers/Game/SkillHandler.cs

With the recent PR #292 it was implemented an trigger function **SetPortal** which is called when entering the tutorial map that sets all portals to invisible and disabled. 
This is an temporary fix so the portal appears after breaking the barrier.

Fix: tutorial barrier portal

---

MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
MapleServer2/PacketHandlers/Game/RideHandler.cs
MapleServer2/PacketHandlers/Game/UserSyncHandler.cs
MapleServer2/Packets/UserMoveByPortalPacket.cs
MapleServer2/Servers/Game/FieldManager.cs
MapleServer2/Tools/GameCommandActions.cs

Suggestions from @Clockworkx 
- Better variables naming;
- Using similar style from **TryParse** in `GameCommandActions`: **ParseShort**, **ParseInt**, **ParseLong**.

Fix: better variables naming

---

MapleServer2/Database/DatabaseContext.cs
MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
MapleServer2/PacketHandlers/Game/ClubHandler.cs
MapleServer2/PacketHandlers/Game/DungeonHandler.cs
MapleServer2/PacketHandlers/Game/FieldEnterHandler.cs
MapleServer2/PacketHandlers/Game/InstrumentHandler.cs
MapleServer2/PacketHandlers/Game/MatchPartyHandler.cs
MapleServer2/PacketHandlers/Game/PartyHandler.cs
MapleServer2/PacketHandlers/Game/RideHandler.cs
MapleServer2/PacketHandlers/Game/UserChatHandler.cs
MapleServer2/Packets/PartyPacket.cs
MapleServer2/Servers/Game/DungeonManager.cs
MapleServer2/Servers/Game/GameSession.cs
MapleServer2/Tools/InventoryController.cs
MapleServer2/Tools/PartyManager.cs
MapleServer2/Types/Party.cs
MapleServer2/Types/Player.cs

This fixes it so parties are only in memory now (removing PartyID from DB) and function to work in memory.
Fixed ensembles - should now be working properly now.
Also as a side note, not sure if it's because of .NET 6, but it had trouble with the determining "Instrument" from some other function that didn't pop up before. This is why I had to change it to define which Instrument in InstrumentHandler
#85 
EDIT:
Fixed an issue where if an item ID exists in your inventory, spawning a new itemID with a different rarity will disregard that rarity, and stack with the existing ItemID's rarity.

Party In Memory Only & Ensemble Performances Fix

---

MapleServer2/Database/DatabaseManager.cs

Missing `Guild` attribute in **DatabaseManager.UpdateCharacter()** .

Fix: Guilds not saving correctly

---

MapleServer2/PacketHandlers/Game/BeautyHandler.cs

Fixes crash when changing eyes/hair for the second time;
Only setting return map if character isn't inside an beauty map.

Fix: Beauty crash and returning to correct map

---

MapleServer2/Types/Player.cs

- First SkillTree TabId for every character is now = 1;

Fix: ActiveSkillTabId not saving correctly

---

MapleServer2/PacketHandlers/Game/FishingHandler.cs

- Fishing was adding a new MasteryExp, which made the packet 4 bytes longer than expected by client.

Fix: Fishing

---

MapleServer2/PacketHandlers/Game/BeautyHandler.cs
MapleServer2/PacketHandlers/Game/Helpers/QuestHelper.cs
MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
MapleServer2/Types/Item.cs

- Fixes #401 ;
- Resolves #381 
- Fixes BeautyHandler to only delete previous beauty item if there is an new one to replace it;
- Transparency bools were always being initialized as an empty array

Fix: transparency badge, BeautyHandler and #401

---

MapleServer2/Packets/ShopPacket.cs
MapleServer2/Types/DismantleInventory.cs
MapleServer2/Types/Item.cs

- Added bool to `Item` constructor so it's possible to create an new Item object without adding it to the database. Fixes #392 
- Checking if index was not found before trying to access the array in DismantleInventory.

Fix: Dismantle & ShopPacket

---

MapleServer2/Database/DatabaseManager.cs
MapleServer2/MapleServer.cs

Fixes #452 
Remaks:
- Is there a central place to put the required version number? Currently I put it in `InitDatabase`
- The original issue suggested returning from `InitDatabase` when the check fails. This does not stop the emulator from running. Should a shutdown be enforced or just let it crash and possibly burn?

fix: add check for mysql version

---

MapleServer2/Data/AuthStorage.cs
MapleServer2/Network/Session.cs
MapleServer2/PacketHandlers/Common/QuitHandler.cs
MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
MapleServer2/PacketHandlers/Game/ChannelHandler.cs
MapleServer2/PacketHandlers/Game/HomeActionHandler.cs
MapleServer2/PacketHandlers/Game/LoadUgcMapHandler.cs
MapleServer2/PacketHandlers/Game/MoveFieldHandler.cs
MapleServer2/PacketHandlers/Game/RequestHomeHandler.cs
MapleServer2/PacketHandlers/Login/CharacterManagementHandler.cs
MapleServer2/PacketHandlers/Login/LoginHandler.cs
MapleServer2/Packets/GuildPacket.cs
MapleServer2/Packets/MigrationPacket.cs
MapleServer2/Packets/ServerEnterPacket.cs
MapleServer2/Packets/ServerListPacket.cs
MapleServer2/Servers/Game/GameSession.cs
MapleServer2/Types/Player.cs

Using the packet **GameToGame**, it's possible to change servers (with different IPs) when changing channels. That's why the current session is closed and then re opened. 
- Now retrieving the player from database when selecting it in `CharacterManagementHandler` and saving it in **AuthData** so it can be shared between **Sessions**.
- When changing channels or anytime **GameToGame** is used, set `player.IsChangingChannel` to true so we don't send login/logout messages.
Fixed packets:
- SERVER_ENTER
- GUILD
- GAME_TO_GAME
- SERVER_LIST

Feat: Channels

---

MapleServer2/Database/SQL/Database.sql

It was previously set to 12, which caused a crash when creating a guild with a longer name :D 
Unsure if I need to do anything else, but I guess if people have an existing DB they can make the change themselves easily enough.

Set max length of name in guilds schema to 25

---

MapleServer2/PacketHandlers/Game/GuildHandler.cs
MapleServer2/Types/Guild/GuildRank.cs

Adds the ability to send guild mail
- Sends to all members including the sender
- Checks that the user has permission to do so, and displays appropriate error message if not
- Checks that the user is in a guild before sending, to avoid sneaky packet manipulating players
- Adds quick helper method to `GuildRank` to see if player's rank has appropriate flag set
- This is useful in a couple other places in `GuildHandler`, but didn't want to create noise in this PR

Implement sending of guild mail

---

Maple2Storage/Json/Constants.json
MapleServer2/Database/Classes/DatabaseAccount.cs
MapleServer2/Database/Classes/DatabaseCharacter.cs
MapleServer2/Network/Session.cs
MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
MapleServer2/PacketHandlers/Login/LoginHandler.cs
MapleServer2/PacketHandlers/Login/ServerEnterPacketHandler.cs
MapleServer2/Packets/DynamicChannelPacket.cs
MapleServer2/Packets/ExperiencePacket.cs
MapleServer2/Packets/PrestigePacket.cs
MapleServer2/Packets/ServerListPacket.cs
MapleServer2/Types/Account.cs
MapleServer2/Types/Currency.cs
MapleServer2/Types/Levels.cs
MapleServer2/Types/Player.cs
MapleServer2/Types/Wallet.cs

- Added a constant for channel count;
- Fixed packet `DynamicChannel`, no more hardcoded 9 channels limit;
- Simplified `Player.Session` initialization in `ResponseKeyHandler`;
- Simplified `Levels` use of **GameSession**, **Player** and **FieldPlayer**

Channel count constant

---

MapleServer2/Database/Classes/DatabaseItem.cs
MapleServer2/Managers/BlackMarketManager.cs
MapleWebServer/Controllers/ItemController.cs
MapleWebServer/Controllers/ProfilesController.cs
MapleWebServer/Controllers/UploadController.cs
MapleWebServer/Program.cs
MapleWebServer/Startup.cs

- Fixed bug with creating UGC items:
- Removed `ItemMetadataStorage` access from `DatabaseItem.ReadItem` function. If the **MapleWebServer** tries to use **ItemMetadataStorage** it'll fail since the metadata wasn't loaded.
- Added missing `SetMetadataValues` in `BlackMarketManager`.

Cleanup: MapleWebServer

---

MapleServer2/Enums/FieldObjectUpdate.cs
MapleServer2/Packets/ExperiencePacket.cs
MapleServer2/Packets/FieldObjectPacket.cs
MapleServer2/Packets/LevelUpPacket.cs
MapleServer2/Packets/RevivalConfirmPacket.cs
MapleServer2/Packets/StatPacket.cs
MapleServer2/Types/Levels.cs

- Added Revival Confirm packet
- Separated Experience Up and Level up packets
- Renamed `FieldObjectUpdate.Type3` to `FieldObjectUpdate.Level`

Fix: Level up packets

---

MapleServer2/PacketHandlers/Game/AttendanceHandler.cs
MapleServer2/Packets/GameEventUserValuePacket.cs

- Swapped from `Parse` to `TryParse`. This should address the crash
- Also now checking if the date is a later date AND not the same date. Previously was only checking Day # (would not work when a new month starts)

Fix: Attendance for different days & Parse first day

---

.github/workflows/dotnet.yml
MapleServer2.Tests/MapleServer2.Tests.csproj
MapleServer2.Tests/Tools/ConditionHelperTests.cs
MapleServer2.sln

I'm making this as a draft as it's a demonstration to show people what a project with unit tests might look like. tl;dr this is an idea that I think is worth investing time in as it provides many benefits.
- Provided that they are comprehensive, they act as a safety net and increase confidence.
- Developers can now freely make changes in ConditionHelper, and if they break existing behaviour, they will know about it instantly without having to manually test anything.
- They encourage good development practices, good code is easily testable code. You can only test via public methods/constructors.
- They are quick and repeatable, and can be automated and used for PR gating.
- They are easy to run, Rider and R# add buttons to run all in a class, or individual tests, or all tests in …

Add unit test project - and example unit tests for ConditionHelper

---

MapleServer2/Commands/Game/ItemCommands.cs
MapleServer2/Managers/Actors/Character.cs
MapleServer2/Types/Item.cs

- Fixes able to equip items with no expiration date
- Prevents player from spawning in an item with a rarity less than 1 or higher than 6 to avoid crashes
- Removes skill Id notice packet being sent when using a skill

Item Equipping and Item Rarity Command Fix

---

MapleServer2/PacketHandlers/Game/SkillHandler.cs
MapleServer2/Types/DamageHandler.cs
MapleServer2/Types/RegionSkillHandler.cs
MapleServer2/Types/SkillCast.cs

- made a bunch of changes to the damage formula to properly use a lot of the common stats used in gearing
- moved isCrit into damage formula
- temporarily added luckCoefficient argument to damage formula. making a new stat for it is recommended
- added a bunch of placeholders for unhandled multipliers that come from buffs. making new stats for them is recommended
- added an unused enum for damage range type (melee/ranged)
- added a stub function for marking a skill as a guaranteed crit
- accidental master pr 👀

Feat: Damage formula - WIP

---

MapleServer2/Database/DatabaseManager.cs

It fixes sql scheme error on MariaDB. (Tested on MariaDB 10.6)
It changes `utf8mb4_0900_ai_ci` to `utf8mb4_unicode_520_ci` if DBMS is `MariaDB`.
Has no effect on MySQL DBMS.

MariaDB support as legacy mode (experimental)

---

MapleServer2/Servers/Game/GameSession.cs
MapleServer2/Types/SkillTab.cs

Added some safe checking nulls of `SkillTab.cs` and `GameSession.cs`
1. When making character, subSkill in SkillTab.cs might be null.
2. Sometimes, when you are closing client OnlineCTS might be null.

Fix: Server crashing after making a character or closing client

---

.github/ISSUE_TEMPLATE/bug_report.md

Use comment tags to hide the guide text from the finished issue.

Fix: issue template
